package com.xywei.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.11
 * 2019-11-04T15:58:11.616+08:00
 * Generated source version: 3.2.11
 *
 */
@WebService(targetNamespace = "http://service.xywei.com/", name = "StudentService")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentService {

    @WebMethod
    @RequestWrapper(localName = "findByIdAndAge", targetNamespace = "http://service.xywei.com/", className = "com.xywei.webservice.service.FindByIdAndAge")
    @ResponseWrapper(localName = "findByIdAndAgeResponse", targetNamespace = "http://service.xywei.com/", className = "com.xywei.webservice.service.FindByIdAndAgeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.xywei.webservice.service.Student> findByIdAndAge(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findById", targetNamespace = "http://service.xywei.com/", className = "com.xywei.webservice.service.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://service.xywei.com/", className = "com.xywei.webservice.service.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.xywei.webservice.service.Student findById();
}
